language: cpp
script: ./build.sh
compiler: gcc
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libboost-thread-dev 
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev 
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - google-mock
      - qtbase5-dev
      - qtdeclarative5-dev
