language: cpp
script: ./build.sh
compiler: gcc
sudo: required
branches:
  only:
  - develop
dist: xenial
addons:
  apt:
    packages:
      - libboost-thread-dev 
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev 
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libgl-dev
      - google-mock
      - libdrm-dev
      
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt571-xenial
  - sudo apt-get update -qq

install:
  - sudo apt-get install -yqq qt57base qt57declarative qt57quickcontrols2 qt57multimedia; source /opt/qt57/bin/qt57-env.sh
  - sudo gem install coveralls-lcov

after_success:
   - cd build &&
     mkdir -p coverage &&
     lcov -c -i -d CMakeFiles -o coverage/app_base.info &&
     bin/kegeratorDisplayUnitTest &&
     lcov -c -d CMakeFiles -o $COVERAGE_DIR/app_cov.info &&
     lcov -a $COVERAGE_DIR/app_base.info -a $COVERAGE_DIR/app_cov.info -o $COVERAGE_DIR/app_total.info &&
     lcov -e $COVERAGE_DIR/app_total.info *main* -o $COVERAGE_DIR/app_main_only.info &&
     coveralls-lcov coverage/app_main_only.info
