language: cpp
script: ./build.sh
compiler: gcc
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libboost-thread-dev 
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev 
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - google-mock
      
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo apt-get install -qq g++-6 qt57-meta-full
