language: cpp
script: ./build.sh
compiler: gcc
sudo: required
before_install:
  sudo apt-get install libboost-all-dev
  sudo apt-get install qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtquick2 qml-module-ubuntu-test
