language: cpp
script: ./build.sh
compiler: gcc
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libboost-thread-dev 
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev 
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - google-mock
      
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt571-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get install -yqq qt57base qt57declarative qt57quickcontrols2
